"""Initial migration with all tables

Revision ID: e22620c75617
Revises: 
Create Date: 2026-04-05 17:12:24.323501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22620c75617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_forms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tag_value', sa.String(length=255), nullable=False),
    sa.Column('type_tags', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('theme', sa.Enum('light', 'dark', 'system', name='themeenum'), nullable=False),
    sa.Column('text_size', sa.Enum('small', 'medium', 'large', name='textsizeenum'), nullable=False),
    sa.Column('show_sub', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('new_followers', sa.Boolean(), nullable=False),
    sa.Column('access_requests', sa.Boolean(), nullable=False),
    sa.Column('birt_after', sa.Boolean(), nullable=False),
    sa.Column('birt_before', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_forms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('type_tag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('url_gift', sa.String(length=2048), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('RUB', 'BYN', 'USD', 'EUR', 'UAH', 'KZT', name='currencyenum'), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('status_is_finished', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('typeprivacy', sa.Enum('public', 'private', 'protected', name='typeprivacyenum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wishlist_id', sa.BigInteger(), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='accessrequeststatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_requester_id'), 'access_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_access_requests_wishlist_id'), 'access_requests', ['wishlist_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subscriber_id', sa.BigInteger(), nullable=False),
    sa.Column('type_sub', sa.Boolean(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_wishlist_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_wishlist_id'], ['wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_subscriber_id'), 'subscriptions', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_target_user_id'), 'subscriptions', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_target_wishlist_id'), 'subscriptions', ['target_wishlist_id'], unique=False)
    op.create_table('wish_wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.BigInteger(), nullable=False),
    sa.Column('wishlist_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wish_reservations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wish_wishlist_id', sa.BigInteger(), nullable=False),
    sa.Column('reserved_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reserved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wish_wishlist_id'], ['wish_wishlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wish_reservations_id'), 'wish_reservations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wish_reservations_id'), table_name='wish_reservations')
    op.drop_table('wish_reservations')
    op.drop_table('wish_wishlist')
    op.drop_index(op.f('ix_subscriptions_target_wishlist_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_target_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscriber_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_access_requests_wishlist_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_requester_id'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_table('wishlists')
    op.drop_table('wishes')
    op.drop_table('user_forms')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags_forms')
    # ### end Alembic commands ###
